### ISSUE TITLE
Trouble building with ESP-IDF 5.1

### ISSUE THREAD

**Issue by flyaruu** [ilikepi63/esp-idf-servo#1]
Hi! My project is on ESP_IDF_VERSION = "release/v5.1", and with that version esp-idf-servo fails to compile.

I can take a stab at making this work, but I am somewhat nooby.

`➜  esp-idf-servo git:(main) ✗ cargo build
   Compiling esp-idf-servo v0.2.4 (/Users/f.lyaruu/git/rust/videos/esp-idf-servo)
error[E0432]: unresolved imports `esp_idf_sys::ledc_clk_cfg_t_LEDC_AUTO_CLK`, `esp_idf_sys::ledc_timer_config_t__bindgen_ty_1`
 --> src/lib.rs:3:5
  |
3 |     ledc_clk_cfg_t_LEDC_AUTO_CLK, ledc_get_duty, ledc_intr_type_t_LEDC_INTR_DISABLE, ledc_mode_t,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ledc_clk_cfg_t_LEDC_AUTO_CLK` in the root
4 |     ledc_set_duty, ledc_stop, ledc_timer_bit_t, ledc_timer_bit_t_LEDC_TIMER_10_BIT,
5 |     ledc_timer_config, ledc_timer_config_t, ledc_timer_config_t__bindgen_ty_1, ledc_timer_rst,
  |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ledc_timer_config_t__bindgen_ty_1` in the root
  |
help: a similar name exists in the module
  |
3 |     ledc_clk_src_t_LEDC_APB_CLK, ledc_get_duty, ledc_intr_type_t_LEDC_INTR_DISABLE, ledc_mode_t,
  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: a similar name exists in the module
  |
5 |     ledc_timer_config, ledc_timer_config_t, mcpwm_timer_config_t__bindgen_ty_1, ledc_timer_rst,
  |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0560]: struct `ledc_timer_config_t` has no field named `__bindgen_anon_1`
  --> src/lib.rs:55:13
   |
55 |             __bindgen_anon_1: ledc_timer_config_t__bindgen_ty_1 {
   |             ^^^^^^^^^^^^^^^^ `ledc_timer_config_t` does not have this field
   |
   = note: available fields are: `duty_resolution`

Some errors have detailed explanations: E0432, E0560.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `esp-idf-servo` (lib) due to 2 previous errors
➜  esp-idf-servo git:(main) ✗ 
`

**Comment by ilikepi63** [comment]
Hey @flyaruu ! Sorry I didn't get a ping about this. Did you manage to get it working at all or get an idea of what the problem was? 

I'll take a little stab at this asap - work has just been a little busy for me :)

**Comment by flyaruu** [comment]
Hey @ilikepi63 , not really, I ended up hand coding the servo stuff (it was for a demo) and that worked. I think it is/was an upstream issue, there was a release (I _think_ esp-idf-sys) that broke some dependencies. I encountered very similar errors elsewhere. Once a fix was released, they all worked again. Possibly esp-idf-servo is similar, but I never revisited.

**Comment by c-solo** [comment]
Hi, have the same issue.
